version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/8.1/Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    networks:
      - webproxy
    depends_on:
      - mysql

  web:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: bobflows.com
      LETSENCRYPT_HOST: bobflows.com
      LETSENCRYPT_EMAIL: bobflows99@gmail.com
    volumes:
      - .:/var/www/html:ro
    networks:
      - webproxy
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - webproxy

networks:
  webproxy:
    external: true

volumes:
  mysql-data:
    driver: local
